/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectosi;

import Arbol.ArbolNario;
import java.io.File;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import javax.swing.JFileChooser;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author jefersson
 */
public class Programador_Eventos extends javax.swing.JFrame {

    /**
     * Creates new form Programador_Eventos
     */
    public double temperatura, humedad, viento, precipitacion, clo;
    private String date;
    public LocalDateTime fecha;
    
    public Programador_Eventos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Date jDateChooser2 = new Date();
        SpinnerDateModel sm =
        new SpinnerDateModel(jDateChooser2, null, null, Calendar.HOUR_OF_DAY);
        jSpinner2 = new javax.swing.JSpinner(sm);
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bienvenidos al programador de eventos. ");

        jLabel3.setText("Fecha y Hora del Evento");

        JSpinner.DateEditor de = new JSpinner.DateEditor(jSpinner2, "HH:mm:ss");
        jSpinner2.setEditor(de);
        jSpinner2.setToolTipText("00:00:00");

        jDateChooser1.setDateFormatString("yyyy-MM-dd");

        jButton1.setText("Evaluar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        int dia = jDateChooser1.getCalendar().get(Calendar.DAY_OF_MONTH);
        int  mes = jDateChooser1.getCalendar().get(Calendar.MONTH)+1;
        int año = jDateChooser1.getCalendar().get(Calendar.YEAR);
        Format formatter = new SimpleDateFormat("HH:mm:ss");
        String hour  = formatter.format(jSpinner2.getValue());
        String[] s = hour.split(":");
        int hora = Integer.parseInt(s[0]);
        int minuto = Integer.parseInt(s[1]);
        fecha = LocalDateTime.of(año, mes, dia, hora, minuto);
        File f = new File("Datos climaticos.xlsx");
        recorrerArchivo ra = new recorrerArchivo(f, fecha);
        
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Programador_Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Programador_Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Programador_Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Programador_Eventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Programador_Eventos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner jSpinner2;
    // End of variables declaration//GEN-END:variables

    public void crearArbol() {
        ArbolNario arbol = new ArbolNario();
        arbol.insertarHijo("", "¿Que PET presenta?", null);
        arbol.insertarHijo("¿Que PET presenta?", "PET", null);
        arbol.insertarHijo("PET", "Muy Frío", "1");
        arbol.insertarHijo("PET", "Frío", "2");
        arbol.insertarHijo("PET", "Fresco", "3");
        arbol.insertarHijo("PET", "Ligeramente Fresco", "4");
        arbol.insertarHijo("PET", "Confortable", "5");
        arbol.insertarHijo("PET", "Ligeramente Cálido", "6");
        arbol.insertarHijo("PET", "Cálido", "7");
        arbol.insertarHijo("PET", "Caluroso", "8");
        arbol.insertarHijo("PET", "Muy Caluroso", "9");
        arbol.insertarHijo("Muy Frío", "Temperatura", "");
        arbol.insertarHijo("Muy Frío", "HR %", "");
        arbol.insertarHijo("Muy Frío", "Viento", "");
        arbol.insertarHijo("Muy Frío", "Precipitacion", "");
        arbol.insertarHijo("Muy Frío", "CLO", "1.0");
        arbol.insertarHijo("Frío", "Temperatura", "");
        arbol.insertarHijo("Frío", "HR %", "");
        arbol.insertarHijo("Frío", "Viento", "");
        arbol.insertarHijo("Frio", "Precipitacion", "");
        arbol.insertarHijo("Frío", "CLO", "");
        arbol.insertarHijo("Fresco", "Temperatura", "");
        arbol.insertarHijo("Fresco", "HR %", "");
        arbol.insertarHijo("Fresco", "Viento", "");
        arbol.insertarHijo("Fresco", "Precipitacion", "");
        arbol.insertarHijo("Fresco", "CLO", "");
        arbol.insertarHijo("Ligeramente Fresco", "Temperatura", "");
        arbol.insertarHijo("Ligeramente Fresco", "HR %", "");
        arbol.insertarHijo("Ligeramente Fresco", "Viento", "");
        arbol.insertarHijo("Ligeramente Fresco", "Precipitacion", "");
        arbol.insertarHijo("Ligeramente Fresco", "CLO", "");
        arbol.insertarHijo("Confortable", "Temperatura", "");
        arbol.insertarHijo("Confortable", "HR %", "");
        arbol.insertarHijo("Confortable", "Viento", "");
        arbol.insertarHijo("Confortable", "Precipitacion", "");
        arbol.insertarHijo("Confortable", "CLO", "");
        arbol.insertarHijo("Ligeramente Cálido", "Temperatura", "");
        arbol.insertarHijo("Ligeramente Cálido", "HR %", "");
        arbol.insertarHijo("Ligeramente Cálido", "Viento", "");
        arbol.insertarHijo("Ligeramente Cálido", "Precipitacion", "");
        arbol.insertarHijo("Ligeramente Cálido", "CLO", "");
        arbol.insertarHijo("Cálido", "Temperatura", "");
        arbol.insertarHijo("Cálido", "HR %", "");
        arbol.insertarHijo("Cálido", "Viento", "");
        arbol.insertarHijo("Cálido", "Precipitacion", "");
        arbol.insertarHijo("Cálido", "CLO", "1.0");
        arbol.insertarHijo("Caluroso", "Temperatura", "");
        arbol.insertarHijo("Caluroso", "HR %", "");
        arbol.insertarHijo("Caluroso", "Viento", "");
        arbol.insertarHijo("Caluroso", "Precipitacion", "");
        arbol.insertarHijo("Caluroso", "CLO", "1.0");
        arbol.insertarHijo("Muy Caluroso", "Temperatura", "");
        arbol.insertarHijo("Muy Caluroso", "HR %", "");
        arbol.insertarHijo("Muy Caluroso", "Viento", "");
        arbol.insertarHijo("Muy Caluroso", "Precipitacion", "");
        arbol.insertarHijo("Muy Caluroso", "CLO", "1.0");
        arbol.imprimirArbol(arbol);
    }
}
